batch_size: 2
feature_extractor_name: deepwalk
id: perslay
model_class: morphoclass.models.CorianderNet
model_params:
  n_features: 64
n_epochs: 100
optimizer_class: torch.optim.Adam
optimizer_params:
  lr: 0.005
  weight_decay: 0.0005
